In [3]:
from sklearn.datasets import make_regression
import pandas as pd
import numpy as np

import plotly.express as px
import plotly.graph_objects as go

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

In [4]:
df = pd.read_csv('Student_Performance.csv', nrows = 100)
df.head()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0

In [5]:
X = df[['Hours Studied', 'Sample Question Papers Practiced']]
y = df['Performance Index']

In [6]:
df.shape

(100, 6)

In [7]:
df.head()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0

In [8]:
fig = px.scatter_3d(df, x='Hours Studied', y='Sample Question Papers Practiced', z='Performance Index')

fig.show()

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=3)

In [10]:
from sklearn.linear_model import LinearRegression

In [11]:
lr = LinearRegression()

In [12]:
lr.fit(X_train,y_train)

LinearRegression()

In [13]:
y_pred = lr.predict(X_test)

In [14]:
# Create grid for plane
x_range = np.linspace(df['Hours Studied'].min(), df['Hours Studied'].max(), 20)
y_range = np.linspace(df['Sample Question Papers Practiced'].min(), df['Sample Question Papers Practiced'].max(), 20)

xx, yy = np.meshgrid(x_range, y_range)

grid = np.c_[xx.ravel(), yy.ravel()]
z = lr.predict(grid)
z = z.reshape(xx.shape)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning:

X does not have valid feature names, but LinearRegression was fitted with feature names

In [15]:
print("MAE",mean_absolute_error(y_test,y_pred))
print("MSE",mean_squared_error(y_test,y_pred))
print("R2 score",r2_score(y_test,y_pred))

MAE 12.758493202532334
MSE 245.9748406692532
R2 score -0.3232279340967952

In [16]:
fig = px.scatter_3d(df,x='Hours Studied',y='Sample Question Papers Practiced',z='Performance Index')

fig.add_trace(
    go.Surface(
        x=xx,
        y=yy,
        z=z,
        opacity=1,
        showscale=False
    )
)

fig.show()

In [17]:
lr.coef_

array([4.0466822, 0.3847288])

In [18]:
lr.intercept_

np.float64(35.20882417456849)